version: '3'
services:
  web:
    image: keymetrics/pm2-docker-alpine:8
    ports: 5000:5000
    volumes:
    - ./app:/app
    links:
    - redis
    - mongo
  redis:
    image: redis
  mongo:
    image: mongo
