FROM arm64v8/alpine

RUN apk add --no-cache nodejs-current
RUN npm install -g pm2
ENV NODE_ENV=production
COPY process.yml .
COPY package.json .
RUN npm install

COPY app/ .

CMD ["pm2-docker", "start", "--auto-exit", "--env", "production", "process.yml", "--web", "9999"]

EXPOSE 3000
EXPOSE 9999

HEALTHCHECK --interval=3m --timeout=3s \
  CMD curl -f http://localhost:3000/health || exit 1
