FROM arm64v8/alpine

RUN apk add --no-cache nodejs-current
RUN npm install -g pm2
ENV NODE_ENV=production
COPY process.yml .
COPY package.json .
RUN npm install

COPY app/ .

CMD ["pm2-docker", "start", "--auto-exit", "--env", "production", "process.yml"]

EXPOSE 3000
